; (throw 'load-error "This file is not meant to be loaded")

(define (print-ln . args)
  (for-each display args)
  (newline))

(define (run-turtle p)
  (print-ln "Running turtle program " p)
  (do ((i 0 (+ i 1)))
      ((= i 10))
    (move i 0))
  (move 10 10)
  (pen-down)
  (move 100 100)
  (pen-up))